### ISSUE TITLE
Simple To-do list

### ISSUE THREAD

**Issue by reznikovl** [brandonnadell/impulse#4]
Subtasks:
- [ ] Ability to add, remove items
- [ ] Working checkboxes
- [ ] Checking an item makes it crossed out
- [ ] Data remains after page refresh (ie backend saves it)
